### ISSUE TITLE
Wybranie Frameworka do projektu

### ISSUE THREAD

**Issue by siemaEko** [PLProjektKompetencyjny/PK_6IO1z_Projekt4_Backend#2]
Należy dodać framework Django do projektu na  gicie.

**Comment by StanislawHorna** [comment]
# Proposal
W związku z tym co @siemaEko przetestował znacznie łatwiej będzie zastosować flask.

## Zalety
- Łatwiejszy niż DJango
- Stworzony typo do tworzenia API

**Comment by StanislawHorna** [comment]
"Po próbach napisania prostego API, stwierdzam że framwork Flask będzie lepszym rozwiązaniem do naszego zadania. Ma on dużo mniejszy próg wejścia, oraz za pomocą pluginów posiada wszystkie potrzebne nam funkcje.

Z pomocą flaska napisałem proste api w niecałe 5 minut.
W Django zajęło to znacznie dłużej."

~ @siemaEko
